fix: 댓글 작성 시 업데이트가 바로 되지 않는 문제 수정
ConceptBe/conceptbe-frontend pull request #128
Opened 2024-04-24 15:13 UTC by yogjin

- 화면에 intersection-ref가 보이지 않으면 invalidate를 해도 업데이트가 되지 않음 (이유는 아직 모름)
- 따라서 margin을 400px(휴리스틱)줘서 ref가 보이도록 수정

## 📄 Summary
댓글 작성 시 업데이트가 바로 되지 않는 문제를 수정합니다.

## 🙋🏻 More

>

2024-04-25 20:19 UTC, semnil5202 requested changes
머리가 지긋지긋한 버그 잡느라 고생 많으셨습니다. 여러 테스트를 해본 결과 위 방식은 page가 증가하는 즉, 10번째에서 11번째 댓글을 작성할 때 무한스크롤이 되지 않더군요. 여러 디버깅을 해본 결과 근본적인 원인은 아래 두 가지 였습니다.

1. useCommentsQuery의 getNextPageParam 갱신 로직 오류
2. useCommentInfiniteFetch의 intersection?.isIntersecting과 queryClient.invalidateQueries 사이의 충돌

## 첫 번째 오류
이 오류의 근본적인 원인은 대댓글입니다. 확인해보니 현재 댓글과 대댓글이 size에 포함되더군요. 즉 댓글 1개에 대댓글 9개면 다음 댓글 작성시 호출엔 `page: lastPageParam.page + 1`이 되서 호출해야합니다. 하지만 현재 갱신 로직은 댓글만 파악하고 있습니다. 이렇다보니 정상적으로 무한스크롤이 되지 않네요. 따라서 댓글과 대댓글 모두를 파악해서 비교하는 아래 로직으로 수정하면 정상 동작합니다. 😇

### useCommentsQuery.ts
```ts
import { useSuspenseInfiniteQuery } from '@tanstack/react-query';

import { http } from '../../../../api/http';
import { CommentParentResponse } from '../../types';

interface GetCommentsProps {
  page: number;
  size: number;
}

const getComments = (feedId: string, { page, size }: GetCommentsProps) =>
  http.get<CommentParentResponse[]>(`/ideas/${feedId}/comments?page=${page}&size=${size}`);

const useCommentsQuery = (feedId: string) => {
  const sizePerPage = 10;
  const { data, fetchNextPage, ...rest } = useSuspenseInfiniteQuery({
    queryKey: ['comments', feedId],
    initialPageParam: { page: 0, size: sizePerPage },
    queryFn: ({ pageParam }) => getComments(feedId, pageParam),
    getNextPageParam: (lastPage, allPages, lastPageParam) => {
      const nextPageParam = { page: lastPageParam.page + 1, size: sizePerPage };
      // 추가된 핵심 로직 ✅
      const commentsCount = allPages.reduce(
        (acc, commentParents) =>
          acc +
          commentParents.reduce(
            (acc, { commentChildResponses }) => acc + commentChildResponses.length,
            commentParents.length,
          ),
        0,
      );

      return commentsCount < sizePerPage * (lastPageParam.page + 1) ? undefined : nextPageParam;
    },
  });

  return { comments: data.pages.flat(), fetchNextPage, ...rest };
};

export default useCommentsQuery;
```
## 두 번째 오류
본문에서 말씀해주신 것처럼 `intersection-ref가 보이지 않으면 invalidate를 해도 업데이트가 되지 않음` 이 부분이 정확히는 `댓글 또는 대댓글 입력 과정에서 intersection-ref가 안보였다가 입력 완료 후 보이는 경우`에만 문제가 됩니다.

댓글 및 대댓글 입력창은 늘어났다가 줄어드는 특성이 있습니다. 그래서 아래와 같이 댓글 입력창이 확대되었을 때는 intersection-ref가 안 보였다가, 입력 완료 후엔 intersection-ref이 다시 보이게 되면서 문제가 생기는 것을 볼 수 있습니다. (콘솔창에 false, true가 intersection-ref 감지 여부입니다.)

![Apr-26-2024 02-57-20](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/7a534be4-df02-4dff-a414-517744529661)

댓글 및 대댓글 입력 완료 후에 성공시 queryClient.invalidateQueries를 수행하죠. 그래서 intersection-ref가 안보이더라도 정상적으로 갱신이됩니다. 아래 영상 참고.

![Apr-26-2024 02-59-33](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/d0e180f7-8a13-4e2f-bed7-dfb0f0118848)

intersection-ref가 보이는 상태에서 댓글 및 대댓글을 작성하면 당연히 문제가 안 됩니다. 아래 영상 참고.

![Apr-26-2024 05-32-00](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/f0a6fc97-bfaa-4320-ae17-414a7f71a2e4)

하지만 위에서 보셨던 것처럼 댓글 및 대댓글을 입력한 직후 intersection-ref가 false 였던게 true로 변경되면서, queryClient.invalidateQueries가 중간에 스킵되고 intersection?.isIntersecting의 fetchCallback이 실행되는 것을 볼 수 있습니다. 아래 사진 참고.

![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/ad80a36a-ca4d-4cc5-88ea-29592f95deab)

즉, 충돌이 나는 것 같습니다. 따라서 queryClient.invalidateQueries가 수행 중일 때 intersection?.isIntersecting의 fetchCallback의 실행을 하지 않도록 다음처럼 코드를 수정하면 정상 동작합니다.

### useCommentInfiniteFetch.ts
```ts
import { useQueryClient } from '@tanstack/react-query';
import { MutableRefObject, useEffect } from 'react';
import { useIntersection } from 'react-use';

const useCommentInfiniteFetch = (
  intersectionRef: MutableRefObject<HTMLDivElement | null>,
  fetchCallback: () => void,
  feedId: string,
) => {
  const queryClient = useQueryClient();
  const intersection = useIntersection(intersectionRef, {
    root: null,
    rootMargin: '0px',
    threshold: 1,
  });

  useEffect(() => {
    // 추가된 핵심 로직 ✅
    const commentState = queryClient.getQueryState(['comments', feedId]);

    if (intersection?.isIntersecting && commentState?.fetchStatus !== 'fetching') {
      fetchCallback();
    }
  }, [intersection, queryClient, feedId, fetchCallback]);
};

export default useCommentInfiniteFetch;
```
마지막으로 Comments.tsx에서 useCommentInfiniteFetch에 `feedId`를 넘겨주시면 됩니다.

```ts
useCommentInfiniteFetch(intersectionRef, fetchNextPage, feedId);
```

수정 후 리뷰 재요청 부탁드립니다.

2024-04-25 20:19 UTC, semnil5202 commented on src/pages/FeedDetail/components/Comments.tsx
>            <EmptyTabContentSection svg={SVGProfileMessageDots} textList={['', '아직 작성된 댓글이 없어요.']} />
여기 위에 35번째줄의 div 태그도 지워주셔야합니다. 주석을 위쪽에는 안 남겼었군요..

2024-04-25 20:19 UTC, semnil5202 commented on src/pages/FeedDetail/hooks/useCommentInfiniteFetch.ts
> +    threshold: 0,
'0px', 1로 초기화 하셔도 됩니다. 디버깅해보니 근본적인 원인이 따로 있었네요. 본문에 남겨두겠습니다.

2024-04-27 13:30 UTC, yogjin commented
오우.. 여기서 commentState?.fetchStatus !== 'fetching' 이게 핵심이군요!
fetch로직이 충돌 안나게하는것
```ts
  useEffect(() => {
    // 추가된 핵심 로직 ✅
    const commentState = queryClient.getQueryState(['comments', feedId]);

    if (intersection?.isIntersecting && commentState?.fetchStatus !== 'fetching') {
      fetchCallback();
    }
  }, [intersection, queryClient, feedId, fetchCallback]);
```
대박입니다 고생하셨습니다!

2024-04-27 15:32 UTC, semnil5202 approved these changes
변경사항 확인했습니다. 후 홀가분하네요. ㅎㅎ 고생많으셨습니다. 👍

2024-04-29 11:58 UTC, merged