Feat/#116: 텍스트 내 하이퍼링크 활성화 기능 추가
ConceptBe/conceptbe-frontend pull request #139
Opened 2024-04-29 12:53 UTC by semnil5202

## 📄 Summary

close #116

> 게시글, 댓글, 프로필 소개 텍스트 내 하이퍼링크 활성화 기능 추가

## 🙋🏻 More

* 추가로 line-height 단위 리팩토링
* 게시글 상세에서 내가 작성한 글일 경우 프로필 라우팅 방지

2024-04-29 14:26 UTC, yogjin requested changes

2024-04-29 14:26 UTC, yogjin commented on src/pages/components/HyperLinkText/HyperLinkText.tsx
> +  const generatedTexts = text.split('\n').map((line, idx) => {
split 로직을 살짝 고쳐야할것 같네요

현재 이렇게 되는 문제가 있네요
<img width="444" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/fe3c90f1-e305-4496-b549-e07fef035f22">

2024-04-29 17:21 UTC, semnil5202 reviewed
ㅇ

2024-04-29 17:21 UTC, semnil5202 commented on src/pages/components/HyperLinkText/HyperLinkText.tsx
> +  const generatedTexts = text.split('\n').map((line, idx) => {
넵 확인했습니다.

2024-04-29 17:51 UTC, semnil5202 commented
추가로 글 작성 직후 Feed ideas의 invalidate가 동작하지 않는 오류 (댓글 및 대댓글과 동일한 오류) 를 보완했습니다.

[c09d5e4](https://github.com/ConceptBe/conceptbe-frontend/pull/139/commits/c09d5e4be0cf80f6260761390a0a2904ccfffc18)

2024-05-04 15:01 UTC, yogjin approved these changes
확인했습니다 수고하셨습니다~

2024-05-04 15:26 UTC, merged