Fix/#15: SignUp 코로케이션 적용 및 회원가입 플로우 오류 수정
ConceptBe/conceptbe-frontend pull request #22
Opened 2024-01-27 08:57 UTC by semnil5202

## 📄 Summary

> 추후 작성 예정

## 🙋🏻 More

>

2024-01-29 14:30 UTC, yogjin requested changes

2024-01-29 14:30 UTC, yogjin commented on src/pages/SignUp/SignUp.page.tsx
>    const { mainSkillQuery, detailSkillQuery, skillLevelQuery, regionQuery, checkboxQuery } = useSignUpQuery();
갠적으로는 `~Query에서` Query는 빼도 된다고 생각합니다

2024-01-29 14:30 UTC, yogjin commented on src/router.tsx
> +        ),
맘에 안들지만.. 저도 글쓰기 PR에서 어쩔수없이 이와 똑같이 적용했습니다.
디자인 시스템 훅에 대해서는 1차 스프린트 끝나고 논의해보시죠!

2024-01-29 14:30 UTC, yogjin commented on src/pages/SignUp/SignUp.page.tsx
> +  const { mainSkills, detailSkills, skillLevels, regions, purposes } = useSignUpQuery();
이미 적용하셨네요.. 커밋 하나하나씩 보다보니 이미 수정된 부분을 리뷰하는 문제가 있군요?!

2024-01-29 14:30 UTC, yogjin commented on src/pages/SignUp/SignUp.page.tsx
> +      if (confirm('잘못된 입력입니다. 입력하신 내용을 다시 한번 확인해주세요.')) return;
어떤 부분이 잘못되었는지 각 상황마다 유저에게 알려주면 좋을 것 같아요.

2024-01-29 14:30 UTC, yogjin commented on src/pages/SignUp/SignUp.page.tsx
>        joinPurposes: checkboxValue.goal.filter(({ checked }) => checked).map(({ id }) => id),
이렇게 매번 필터하고 매핑하는 로직이 많은데요, 저도 글쓰기 기능 구현할때 똑같이 했었어요.
근데 좀.. 코드 작성하면서도 이게 맞나.. 라는 생각이 계속 들었습니다.
디자인 시스템 훅을 사용하다보니 어쩔 수 없는 것 같은데..ㅠ
혹시 어떻게 생각하시나요?

2024-01-29 14:30 UTC, yogjin commented on src/pages/SignUp/hooks/useSignUpQuery.ts
음 쿼리 훅도 이렇게 페이지 별로 나누셨군요.
저는 쿼리는 따로 queries, mutations 이렇게 나누었는데, 생각해보니 코로케이션 하려면 쿼리도 이렇게 배치해야겠네요.
수정해서 PR 올리겠습니다

2024-01-29 14:30 UTC, yogjin commented on src/pages/SignUp/SignUp.page.tsx
> +  });
추후 에러 상황에 대한 고려도 필요해보입니다.

2024-01-29 14:30 UTC, yogjin commented on src/pages/SignUp/SignUp.page.tsx
> +  });
아 그리고 mutation 분리의 경우 제 글쓰기 PR에서 함께 보시죠!

2024-01-29 14:30 UTC, yogjin commented
세부 스킬이 중복되네요
<img width="321" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/ecf74372-d2d6-43e0-b564-f471857dbc92">

2024-01-29 14:32 UTC, yogjin commented
회원가입 시 프로필 설정할때 밑에 네비게이션이 안보여야할 것 같아요.
<img width="330" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/03b6e0b3-d699-446a-9201-cce2f1625304">
근데 피드 글 불러오는 api는 auth가 필요없던데.. 로그인 안해도 글을 볼 수 있게 해야하는걸까요..? 잘 모르겠네요.

2024-01-29 14:36 UTC, yogjin commented
피그마에 모달창이 따로 있던데, 현재는 `confirm`으로 대신하고있네요.
디자인 시스템에 모달 만들어야하는거죠?
<img width="396" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/35a38e52-a88d-4c03-a4c0-361fafd5277d">
저도 일단 임시로 피그마에서 명시해놓은 토스트대신 `alert` 을 사용하긴 했습니다.. (토스트는 피그마 디자인이 없었습니다)

2024-01-29 14:38 UTC, yogjin commented
프로필 사진 등록은 1차 mvp가 아닌가요?
<img width="96" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/0dc3cec0-da0e-4951-b601-a8de9f7ab2fe">

2024-01-29 14:42 UTC, yogjin commented
회원가입 시에 개인정보 수집 및 이용 동의와 서비스 이용약관을 클릭했을때 나오는 바텀시트가 스크롤이 안되고 있네요.
(회원가입 PR 이지만 우연히 발견해서 코멘트 남겼습니다)
<img width="331" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/fc557e51-e59b-4a89-87dd-c43ccd418a5e">
<img width="348" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/e10dcdff-3b0a-4988-9937-1a98a544e9db">

2024-01-29 14:46 UTC, yogjin commented
현재 세부 스킬에 디자인 선택하면 터지네요. 확인부탁드려요 (DB 데이터 문제일까요?) map 할때 터지는것 같습니다.

2024-01-29 14:47 UTC, yogjin commented
`가입 목적` 으로 수정부탁드려요
<img width="350" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/bdf87b72-c0a2-4dda-be44-456be44c7fc9">

<img width="485" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/6e0ec052-b7c9-47c0-983f-6878083c4fd3">

2024-01-29 15:17 UTC, semnil5202 commented on src/pages/SignUp/SignUp.page.tsx
> +  });
아하 확인했습니다. 해당 방식으로 수정 후 다시 요청할께용~~ 에러 상황에 대해서는 아래 form 에러 핸들링 할 때 한 번에 답변드리겠습니다.

2024-01-29 15:17 UTC, semnil5202 commented on src/pages/SignUp/SignUp.page.tsx
> +  const { mainSkills, detailSkills, skillLevels, regions, purposes } = useSignUpQuery();
예아.. 저도 그거 모르고 커밋에 리뷰남겼다가 바로 Outdated 됐던 적이 있었네여

2024-01-29 15:17 UTC, semnil5202 commented on src/pages/SignUp/SignUp.page.tsx
> +      if (confirm('잘못된 입력입니다. 입력하신 내용을 다시 한번 확인해주세요.')) return;
네네 위 useMutation 에러 상황에 대한 것과 같이 답변을 드리면 이 부분을 디자이너 분과 한 번 얘기해봐야할것같습니다. (1차 이후)

현재 에러 케이스에 대한 시안이 거의 없어서 이 부분도 임시로 confirm으로 처리 했습니다. 크게 봐서 404 페이지나, 로그인 토큰 만료 시 로그인 페이지로 이동할 때 등등 논의가 필요한 상황이라 논의 이후에 Errorboundary와 함께 일괄 적용하시는게 어떨지 제안드립니다~~

2024-01-29 15:17 UTC, semnil5202 commented on src/pages/SignUp/SignUp.page.tsx
>        joinPurposes: checkboxValue.goal.filter(({ checked }) => checked).map(({ id }) => id),
저도 이 부분은 설계 미스인 것 같습니다.. 오로지 클라이언트 단 상태로만 처리가 가능할 줄 알았는데 초기값을 서버에서 받아온 걸로 세팅해야하는 순간부터 불필요한 반복문이 많아졌네요. 1차 이후에 같이 논의해보시죵~~

2024-01-29 15:17 UTC, semnil5202 commented on src/pages/SignUp/hooks/useSignUpQuery.ts
아하 이 부분도 한 번 의견을 나눠보고 싶은데 파일 뎁스를 생각해서 hooks 에 모두 둘지.. 말씀하신 것처럼 queries, mutations, apis 등 한 번 더 뎁스를 들어갈지 고민이네요.

2024-01-29 15:29 UTC, semnil5202 commented
1. 스킬 중복은 생각지도 못했네요 좋은 지적 감사드립니다.👍👍
2. 네비게이션 수정해놓겠습니다~ 피드 조회는 로그인은 필요 없고 그 이외에 나머지 페이지에서는 필요하다고 생각하시면 될 것 같습니다. 피그마 기획 파트에 있습니다.
![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/5c1f46af-78b9-4f89-8cf5-8da65a832ae1)
3. 프로필 수정 말씀하시는걸까용? 등록은 현재 되어있는 상태입니다. 카카오 기본 프로필 사진인 것 같아요~ 수정은 S3 등이 필요할 예정이라 1차 이후입니다.
4. 네.. 세부 스킬 부분 빼먹었습니다. 그 부분 수정하면서 스킬 중복도 같이 해결해놓겠습니다~
5. 오우 꼼꼼한 확인 감사드립니다~!

이렇게 짧은 시간 내에 이정도의 리뷰를 주시다니.. ㅎㄷㄷ 아무튼 야무진 리뷰 감사드립니다~!! 👍👍

2024-01-29 19:14 UTC, semnil5202 commented
### 리팩토링 요약
- [x] 세부 스킬 중복 오류 수정
- [x] 세부 스킬 대분류에 맞게 상세 분류 표시 및 해당 기능 오류 수정
- [x] 세부 스킬 대분류 수정시 상세분류, 숙련도 초기화 (상세분류까지 선택 후 대분류를 변경할 경우 오류로 이어질 수 있음)
- [x] confirm 대신 alert로 일괄 수정
- [x] SignUp 타입 파일 코로케이션 적용
- [x] 네비게이션 회원가입 페이지에서 숨기기
- [x] 가입 목적 라벨 수정 (목적 -> 가입 목적)
- [x] mutation 훅 분리 (post api 함수와 네이밍 중복으로 mutate란 prefix 붙임)

미흡한 부분이나 궁금한 부분이 있다면 리뷰 남겨주세용~~ 🙇🏻‍♂️

2024-01-30 02:33 UTC, yogjin requested changes
확인했습니다~
다시 리뷰 남겨놓은 부분만 확인해주세요!

2024-01-30 02:33 UTC, yogjin commented on src/pages/SignUp/hooks/useSignUpQuery.ts
>  ];
이 데이터들 프론트에서 관리하기로 했나요?
저는 글쓰기할때 region을 서버에서 받아왔습니다. region도 그렇고 skill depth도 한번 확인해주셔야할 것 같아요.

2024-01-30 02:33 UTC, yogjin commented on src/pages/SignUp/hooks/useSignUpQuery.ts
>  };
받은 쿼리 데이터를 가공해야할때 사용하는 useQuery option `select`가 있습니다.
```tsx
const useSignUpQuery = () => {
  const { data } = useSuspenseQuery({
    queryKey: ['GetSignUp'],
    queryFn: getSingUp,
    select: (data) => {
      const { mainSkills, detailSkills } = convertSkillQuery(data.mainSkillResponses);
      const purposes = convertCheckboxQuery(data.purposeResponses);

      return {
        mainSkills,
        detailSkills,
        skillLevels: SKILL_DEPTH_THREE_LIST,
        regions: REGION_LIST,
        purposes,
      };
    },
  });

  return data;
};
```
이렇게 바꿔주면 좋을 것 같아요.

2024-01-30 02:33 UTC, yogjin commented on src/pages/SignUp/types/index.ts
> +}
왜 객체로 바뀌었는가와는 별개로, 
index signiture에 대해 어떻게 생각하시나요?
저는 보통 Record를 사용하는 편이긴 합니다.
```ts
export type DetailSkills = Record<number, DetailSkillOption[]>;
```

2024-01-30 02:33 UTC, yogjin commented on src/pages/SignUp/service/convertSignUpQuery.ts
> +    detailSkills,
왜 객체로 바뀌었나요?

2024-01-30 02:37 UTC, yogjin commented on src/pages/SignUp/hooks/useSignUpMutation.ts
> +export default useSignUpMutation;
네이밍 중복되어 `mutate` prefix 를 붙이셨네요.
저는 axios fetch 함수를 `_postSignUp`와 같이 선언하고,
`useSignUpMutation` 에서 `mutate: postSignUp` 으로 내보내는걸 좋아합니다.
또 react-query를 사용하는 이상 _postSignUp은 단독으로 사용할 일이 거의 없을 것 같아요.

2024-01-30 07:31 UTC, semnil5202 commented on src/pages/SignUp/hooks/useSignUpMutation.ts
> +export default useSignUpMutation;
오호 언더바를 활용한 네이밍 신박하군요. axios fetch 함수를 직접적으로 쓸일이 없다면 위와 같은 방식도 좋아보입니다. post 함수는 아니지만 KakaoRedirect 페이지에서 axios fetch 함수만 사용하는 경우가 있어서요. 이렇게 혼용되는 경우에는 어떻게 처리하시나여?

2024-01-30 07:31 UTC, semnil5202 commented on src/pages/SignUp/hooks/useSignUpQuery.ts
>  ];
네네 현재 서버에서 받아오는 값은 대표스킬의 대분류, 세부 스킬의 대분류, 상세분류 총 세 가지 입니다. 글쓰기할때는 또 달라졌군요.. 이 부분도 추가적으로 얘기해봐야할 것 같습니다.

2024-01-30 07:31 UTC, semnil5202 commented on src/pages/SignUp/hooks/useSignUpQuery.ts
>  };
아하 위 상황은 의도하여 select에 직접적으로 위치시키지 않았습니다. select에 위치 시켜도 상관없으나 여러 쿼리에서 가져온 값을 가공할 때는 select 문 밖에서 처리해야만 하니 통일된 형태를 유지하기 위해 일괄적으로 모두 select 문 밖에서 처리했었습니다.

쓰다보니 굳이 select 문에서 처리할 수 있는데 밖에서 처리해야하나.. 라는 생각도 드네요. 이 부분은 수정해두겠습니다.

2024-01-30 07:31 UTC, semnil5202 commented on src/pages/SignUp/types/index.ts
> +}
오우 Record를 잊고있었네요. 생각해보니 저도 Record를 자주 사용했던 것 같습니다. index signature에 어떤 단점이 있다고 들었는데 정확하게 기억이 나질 않는군여 혹시 아시는 것이 있나영?

2024-01-30 07:34 UTC, semnil5202 commented on src/pages/SignUp/service/convertSignUpQuery.ts
> +    detailSkills,
detailSkills 가 드롭다운에서 쓰이는 형태가 `detailSkills[선택한대분류스킬id]` 형태입니다. 따라서 제가 이전에 작성했던 배열은 잘못된 방법이였고 그로 인해 오류가 발생했던 것입니다. 객체의 키 값을 대분류 스킬 id로 두기위해 객체 형태로 변경하였습니다.

(결과적으로 사용하는 방법은 동일합니다. 애초에 객체형태로 사용해야했던걸 실수로 배열로 두어 오류가 터진 것입니다.)

2024-01-30 07:42 UTC, yogjin commented on src/pages/SignUp/hooks/useSignUpMutation.ts
> +export default useSignUpMutation;
음.. 그런 경우에 저는 그냥 똑같이 사용했던거 같아요.
저희들끼리 언더바 붙은 함수는 axios fetch라고 알고있으면 문제없을듯 합니다.

2024-01-30 07:58 UTC, yogjin commented on src/pages/SignUp/types/index.ts
> +}
인덱스 시그니처는 동적으로 받아오는 데이터에 한해 사용하면 괜찮아서, 사실 이 경우에 사용해도 괜찮다고 생각합니다.
하지만 property가 number 하나인 경우라서 Record도 좋다고 생각했어요.
단점은 [이 포스팅](https://noah-dev.tistory.com/9#3.%20%EC%9D%B8%EB%8D%B1%EC%8A%A4%20%EC%8B%9C%EA%B7%B8%EB%8B%88%EC%B2%98%EC%9D%98%20%EB%8B%A8%EC%A0%90-1)을 보시면 좋을 것 같습니다.

2024-01-30 08:01 UTC, yogjin commented
확인했습니다~
나머지 적용하실 부분 적용하시고 머지하시죠!

2024-01-30 08:02 UTC, yogjin approved these changes

2024-01-30 09:19 UTC, semnil5202 commented on src/pages/SignUp/hooks/useSignUpMutation.ts
> +export default useSignUpMutation;
좋습니다. 수정해두겠습니답~~

2024-01-30 09:55 UTC, merged