Feat/#13 글쓰기 페이지 api 연결
ConceptBe/conceptbe-frontend pull request #25
Opened 2024-01-29 12:41 UTC by yogjin

## 📄 Summary

>

## 🙋🏻 More

>

2024-01-30 15:47 UTC, semnil5202 requested changes
고생많으셨습니다~~ 👍 몇 가지 피드백 드렸어요.

확인해보시고 궁금하거나 문제가 있는 부분은 카톡으로 알려주세용~

2024-01-30 15:47 UTC, semnil5202 commented on src/components/Card/NewIdeaCard/NewIdeaCard.tsx
> +        {isBookmarked ? <SVGFeedScrap /> : <SVGFeedUnScrap />}
내가 작성한 카드와 남이 작성한 카드를 분리하실 계획이시군여. 이 부분은 분기처리 로직이 복잡해질 것 같아 저도 동의합니다.

이 부분이 저도 아직 어려운데 사용하신 SVGFeedScrap 컴포넌트가 FeedDetail에 아래에서 사용되는 SVG 컴포넌트입니다. 따라서 아이디어 카드에서 사용되는 SVG 컴포넌트는 SVGScrap24와 SVGScrapFilled24 입니다.

![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/a31397b4-8e6c-48b8-8565-104b6fc2635f)

1~2px 차이로 서로 나뉘어져있더군요.. SVGScrap24는 Feed 외에도 프로필 페이지 등에서도 사용이 되서 위와 같은 네이밍이 된 것 같습니다. 이 부분은 저도 디자인시스템으로 옮기면서 좀 더 상세하게 분류해놨지만, 솔직히 헷갈려서 기존에 작업하신 내용들을 그대로 두고 있습니다. 1차 이후에 디자이너 분과 해당 컴포넌트를 통일을할지 아니면 SVG 네이밍 컨벤션을 빡세게해둘지 정해봅시다.

2024-01-30 15:47 UTC, semnil5202 commented on src/hooks/queries/useBestIdeasQuery.ts
> +  // return bestIdeas;
혹시 몰라서 남겨둔 것일까요?

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/Write.tsx
> +  const canSubmit = branchIds.length > 0 && purposeIds.length > 0 && !!cooperationWay;
어마무시하군요..; 회원가입은 그래도 한 두번 정도였는데 글쓰기는 장난아니네요.

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/Write.tsx
> +    }
혹시 10개 이상은 선택할 수 없다는 내용이 있나요?? 제가 확인하기로는 안 보여서용

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/Write.tsx
> +                <TeamLabel>
key 오류 나는것 같아요~~

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/components/Header.tsx
> +  };
handleClickCheckButton과 onClickCheckButton의 네이밍이 잘 와닿지가 않는 것 같습니다. Write에 국한된 Header이니 글쓰기 Post와 관련된 네이밍이 어떨까요?

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/Write.tsx
> +          />
분야 목적 협업방식 세 가지 필드가 필수 입력 필드인데, 필수 입력 표시가 누락된거 같습니다. 각 Container에 `required` 속성 주시면 됩니다.

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/components/RecruitmentPlaceSection.tsx
> +const RecruitmentPlaceSection = ({ places, selectedPlace, onPlaceChange }: Props) => {
아하 Container도 원래 이런식으로 나누고자 하신거군요. Suspense 구조도 챙기고.. 좋습니다. 어떤 말씀이었는지 잘 와닿네요.

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/components/TitleAndIntroduceSection.tsx
> +        <BodyTextarea
<img width="450" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/97b5ed5f-c388-4aeb-9304-80e1a2f6575d">

![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/af4045ef-8b07-492d-9ff4-6fc58556b3dd)


위 사진과 같이 제목 입력 높이가 맞지 않습니다. Divider에 마진값이 있는 것 같아요. 확인해보니 8px씩 있습니다. top, bottom 속성을 지정하지 않았으면 마진이 따로 없을텐데 어떤 이유에 생긴건지 확인이 필요해보입니다.

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/hooks/mutations/usePostIdeasMutation.ts
> +type PostIdeaError = AxiosError<{ message: string }>;
서버에서 내려준 에러 메세지를 타입으로 지정해주기 위해 요런식으로도 사용할 수 있군요. 배워갑니다~~ 👍

2024-01-30 15:47 UTC, semnil5202 commented on src/pages/write/hooks/mutations/usePostIdeasMutation.ts
> +};
apis 폴더에 두는 것보다 위와 같은 형식을 더 선호하시나요?

headers는 api/http 내부에 axios.create 부분에 작성되어 있을텐데 한 번 더 작성하신 이유가 있을까요?

2024-01-30 15:50 UTC, semnil5202 commented
모집 지역은 필수 값이 아닌데 필수로 되어있는 것 같더군요. 이 부분도 디자인시스템의 설계상 오류일려나요? 유저가 선택하지 않으면 dropdownValue[key] 의 값이 빈 문자열일테니.. 기본값이 전국으로 되어있는데 이는 저희 입장에서 초기값이 전국인것이고, 드롭다운을 펼치는 순간 저 전국은 다시 선택할 수가 없어서 고민이네요.

원래 초기값의 용도는 '지역 선택' 등과 같이 드롭다운의 역할을 알려주는것인지라 위와 같은 경우에선 드롭다운의 첫 번째 값으로 가야하지 않나 싶네요. 어떻게 생각하시나요?

2024-01-30 20:07 UTC, semnil5202 commented on src/pages/write/components/TitleAndIntroduceSection.tsx
> +        <BodyTextarea
이 부분 확인해보니 hr 태그 자체의 속성이었습니다. 게시글 상세 PR 올리면서 reset.css에 추가해둘테니 수정하지 않으셔도 좋습니다.

2024-01-30 20:13 UTC, semnil5202 commented
Write 페이지 파일명 임시 컨벤션에 맞게 Write.page.tsx 또는 WritePage.tsx로 수정 부탁드리고 컴포넌트명도 Page postfix 붙여주세요~

2024-01-31 05:41 UTC, yogjin commented on src/pages/write/Write.tsx
> +    }
피그마 `디자인_ing`에 명시되어 있습니다.
<img width="299" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/3e2bba65-bbb8-4456-af6a-08a033e87a6e">

2024-01-31 05:51 UTC, yogjin commented on src/pages/write/components/Header.tsx
> +  };
음.. 그 부분을 사용하는 쪽에서 드러낼 수 있다고 생각했습니다.
<img width="694" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/03461a36-0c0b-47bf-b763-8d47061cccfa">
헤더가 Write에서만 사용하긴 하지만, Header 자체만의 디자인을 봤을때 단순 체크버튼이라, prop 네이밍으로 `onClickCheckButton` 이 적절하다고 생각했습니다.
<img width="328" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/c1567149-5d2c-47e6-ab5b-156f5dc236f7">
반면에 도메인 중심적으로 `onClickWriteIdeaCheckButton`? 이런식으로 지어도 되겠지만, prop이 조금 길어지는 느낌을 받았습니다. 네이밍이 참 어렵네요.
글쓰기 Post와 관련된 네이밍으로 지으면 어떤 장점이 있을까요?

2024-01-31 05:59 UTC, yogjin commented on src/pages/write/Write.tsx
> +          />
오.. 자동으로 디자인도 되는군요?
아주 좋습니다

2024-01-31 06:06 UTC, yogjin commented on src/pages/write/components/RecruitmentPlaceSection.tsx
> +const RecruitmentPlaceSection = ({ places, selectedPlace, onPlaceChange }: Props) => {
맞습니다.
원래 필터부분 전체를 나누고 싶었습니다.
(제목, 내용은 서버에서 받아올 데이터가 없으니 바로 보여주고, 필터부분은 `Suspense` 처리)
<img width="331" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/9bef92c1-6825-488e-965b-c3bda264da3f">
`RecruitmentPlaceSection` 은 나눠질 필터부분에 선언될 더 세부적인 섹션이라고 보시면됩니다.

2024-01-31 06:07 UTC, yogjin commented on src/pages/write/hooks/mutations/usePostIdeasMutation.ts
> +type PostIdeaError = AxiosError<{ message: string }>;
제네릭으로 넣을 수 있는걸로 아는데, 일단 임시라서 저렇게 했습니다.
에러 메시지 형식을 백엔드와 논의해야할 것 같습니다.

2024-01-31 06:13 UTC, yogjin commented on src/pages/write/hooks/mutations/usePostIdeasMutation.ts
> +};
대부분의 경우 fetch api를 react-query 훅이 감싸진 형태로 이용한다고 생각해서 저렇게 두고 있습니다.
`headers`는 당시에 안넣으니까 token이 안들어갔었는데, 지금 해보니까 되네요.. 아마 hmr 문제였던거 같습니다. 수정했습니다!

2024-01-31 06:46 UTC, yogjin commented
> 모집 지역은 필수 값이 아닌데 필수로 되어있는 것 같더군요. 이 부분도 디자인시스템의 설계상 오류일려나요? 유저가 선택하지 않으면 dropdownValue[key] 의 값이 빈 문자열일테니.. 기본값이 전국으로 되어있는데 이는 저희 입장에서 초기값이 전국인것이고, 드롭다운을 펼치는 순간 저 전국은 다시 선택할 수가 없어서 고민이네요.

원래 초기값의 용도는 '지역 선택' 등과 같이 드롭다운의 역할을 알려주는것인지라 위와 같은 경우에선 드롭다운의 첫 번째 값으로 가야하지 않나 싶네요. 어떻게 생각하시나요?

제 생각엔 설계는 (현재는) 문제 없다고 생각합니다. 
dropdown 선택 옵션들은 대체로 string 그 자체로 유니크 하기때문입니다.
전국을 다시 선택할 수 없는 이유는 현재 백엔드에서 내려주는 데이터에서 "전국"이 없어서 생기는 문제입니다.
즉 드롭다운의 첫번째 값을 "전국"으로 정했던건데, 이 부분은 데이터 추가되면 해결될 것 같네요.

2024-01-31 06:54 UTC, yogjin commented on src/hooks/queries/useBestIdeasQuery.ts
> +  // return bestIdeas;
피드쪽 쿼리라서, 관련 PR(#26)이 따로 올라갈 예정입니다.
주석 삭제되고 코로케이션도 적용되었습니다.

2024-01-31 06:57 UTC, yogjin commented on src/components/Card/NewIdeaCard/NewIdeaCard.tsx
> +        {isBookmarked ? <SVGFeedScrap /> : <SVGFeedUnScrap />}
음.. 그렇군요?
`SVGScrap24`로 적용했습니다!

2024-01-31 07:34 UTC, semnil5202 commented on src/pages/write/components/Header.tsx
> +  };
아하 버튼 자체만 보면 현재의 네이밍이 더 나은 것 같습니다. 그대로 진행하시죱~~

2024-01-31 07:39 UTC, semnil5202 approved these changes
변경사항 모두 확인했습니다 👍👍

2024-01-31 10:10 UTC, merged