Feat/#39: 마이페이지(내 프로필) 기능 구현
ConceptBe/conceptbe-frontend pull request #42
Opened 2024-03-01 12:07 UTC by yogjin

채용 과정땜에 바쁘지만 힘내봅시다~
## 📄 Summary
#39 에 적힌 체크리스트 보면서 리뷰하시면 될 것 같아요!
<img width="200" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/cc2dcb01-88cb-49c5-b934-12d3889ea398">

## 🙋🏻 More

>

2024-03-02 16:42 UTC, semnil5202 requested changes
고생많았어요~~ 👍 feed 페이지와 profile 페이지에서 에러가 발생해서 UI로 동작하는 것을 확인하진 못했지만 코드 레벨에서 분석해보며 리뷰를 남겼습니다.

컴파운드 컴포넌트 패턴과 컨텍스트를 활용하여 컴포넌트 재사용을 한 점이 인상 깊네요. 에러가 발생하는 지점은 ⚠️ 표시로 리뷰했습니다.

수정 후 리뷰 재요청해주세요~

2024-03-02 16:42 UTC, semnil5202 commented on src/components/Spinner/Spinner.tsx
> +  </Position>
야무진 스피너군요 👍👍 혹시 styled 컴포넌트 네이밍을 어떤식으로 가져가시나요?

2024-03-02 16:42 UTC, semnil5202 commented on src/main.tsx
> +    <ReactQueryDevtools initialIsOpen={false} />
사용해보지 않아서 그런데 분석이 필요할 때 그때 그때 true로 변경하여 사용하나여?

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/components/NewIdeaCard/compound/Profile/Profile.tsx
> +          </Box>
svg 파일을 디자인시스템에서 React Component로 내보내서 상태로 분기처리가 필요하군요. default로 string으로 뺀다음 불러오는 쪽에서 React Component로 활용하는 방법을 사용하면 다음과 같은 구문으로 처리해볼 수도 있겠네요. svg 파일을 React Component로 export 한거에 불편함은 없으신가요?

```suggestion
          <Box width={36} height={36} overflow="hidden" borderRadius="0 150px 150px 0">
            <Img
                src={profileImageUrl}
                onError={(e: SyntheticEvent<HTMLImageElement, Event>) => {
                  e.currentTarget.src = SVGLoginDefaultProfile;
            }} />
          </Box>
```

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/components/NewIdeaCard/compound/Content/Content.tsx
> +  const isTeamRecruitmentsExist = teamRecruitments.length > 0;
⚠️ 현재 teamRecruitments 이 undefined 여서 length 프로퍼티를 읽어드리는 부분에서 에러가 발생하고 있습니다. 백엔드 작업이 머지 된 이후부터 발생하는데 확인이 필요할 것 같습니다.

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/components/NewIdeaCard/compound/Content/Content.tsx
> +      ? [...badges.slice(0, 5), <Badge key="모집중">+{badges.length - 5} 모집중</Badge>]
제 로컬 환경에서는 `+{badges.length - 5} 모집중` 부분에서 `Type 'number' is not assignable to type 'string'.`라는 타입 에러가 발생하고 있습니다. 실제론 정상 동작하고 있는 것 같은데 쿠마 환경에서는 발생하지 않나여?

무슨 문제인가 했더니 Badge 컴포넌트 children을 string으로만 국한시켜서 발생하는 타입문제군요.. `+{badges.length - 5} 모집중` 이면 숫자 값이 있어서 string 타입이 아니라 number | string 타입으로 인식되는 모양이군요? 이 부분에 대해서 아시는게 있다면 공유 부탁드립니다.

추가로 Badge 컴포넌트 children props 를 string에서 string | number로 열어두겠습니다.

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/components/NewIdeaCard/compound/Content/ContentEditDropdown.tsx
> +        <SVGPencil16 />
👍

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/components/NewIdeaCard/compound/Footer/Footer.tsx
> +  };
컴포넌트 외부에 선언해도 되지 않을까요? 저도 이 함수를 자주 사용할 것 같아서 유틸로 빼주시면 더 좋을 것 같습니다. (현재는 제 작업물엔 jsx 내부에 삼항연산자로 되어 있습니다.)

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/feed/components/BestIdeaCardListSection/BestIdeaCardListSection.tsx
> +      </Suspense>
Suspense를 Section 컴포넌트 내부에 사용하기 위해 한 파일에 두 개의 컴포넌트를 작성하신걸까요?

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/feed/hooks/mutations/useDeleteBookmarkIdea.ts
> +      queryClient.invalidateQueries({ queryKey: ['members', 'detail', memberId, 'bookmarkedIdeas'] });
혹시 키 네이밍을 어떤 방식으로 하시나요?

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/feed/types/index.ts
> +  createdAt: string; // 생성시각,
Date 객체에서 string 타입으로 바뀌었군요? 서버에서 데이터를 가공해서 내려주는 것 같진 않은데 이유가 있을까요?

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/profile/Profile.page.tsx
> +                <Suspense fallback={<></>}>
서스펜스 fallback을 빈 태그로 두신 이유가 있을까요?

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/components/NewIdeaCard/NewIdeaCardContext.tsx
> +
컨텍스트를 직접 내보내지 않고 사용하는 훅을 내보내는 방법 되게 유익하게 봤습니다. 👍 이런 방법이 조금 더 깔끔해보이는군요. 아래 훅들은 postfix로 context가 붙는데 이 훅은 컨텍스트를 사용함에도 postfix가 없어 사용처에서 헷갈릴수도 있을거 같아요.

그리고 확장자가 tsx로 되어있다보니 제 로컬에는 아래와 같은 린트 경고가 발생하네요. (아래 훅들도 마찬가지로 경고가 발생합니다.)
![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/bef74f52-a378-45c5-8660-6b76e93d47cc)

ts 확장자 대신 tsx를 쓰신 이유가 있을까요?

2024-03-02 16:42 UTC, semnil5202 commented on src/pages/components/NewIdeaCard/NewIdeaCard.tsx
> +    </NewIdeaCardContext.Provider>
feed와 profile 페이지에 공통적으로 사용되는 컴포넌트를 컴포넌트 내부에 분기처리 로직을 두지 않고 컴파운드 + 컨텍스트 형태로 처리하셨군요?! 컴파운드 컴포넌트 활용의 좋은 예이지 않을까 생각이 드네요. 인사이트 해갑니다. 👍

2024-03-02 16:46 UTC, semnil5202 commented
아 추가로 공통 컴포넌트를 pages/components 디렉토리 위치로 두셨는데, src/components와 경계가 모호해서, 공통 컴포넌트의 디렉토리 위치를 어떤식으로 가져가는게 좋을지 의논해보면 좋을 것 같습니다.

2024-03-03 07:26 UTC, yogjin commented on src/components/Spinner/Spinner.tsx
> +  </Position>
보통 맨 바깥을 ~Container 로 붙이긴하는데, 이 Spinner는 네이밍이 조금 달라졌네요.
Position을 이전에 추가해서 그냥 저렇게 붙였습니다.
또 저는 `S.` prefix 붙이지 않고 그냥 작성하는 편입니다.

2024-03-03 07:27 UTC, yogjin commented on src/main.tsx
> +    <ReactQueryDevtools initialIsOpen={false} />
<img width="1288" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/a2b76fcc-f652-4a52-bb04-abe9d4aba8bb">

Open이 아마 이렇게 열려있는 상태를 의미할거에요.
분석이 필요하면 오른쪽 아래 버튼을 클릭하면 열립니다!

2024-03-03 07:30 UTC, yogjin commented on src/pages/components/NewIdeaCard/compound/Profile/Profile.tsx
> +          </Box>
넵 불편함은 없는데, 이 방법 괜찮은 것 같습니다.
적용해볼게요.

2024-03-03 07:33 UTC, yogjin commented on src/pages/feed/hooks/mutations/useDeleteBookmarkIdea.ts
> +      queryClient.invalidateQueries({ queryKey: ['members', 'detail', memberId, 'bookmarkedIdeas'] });
키 팩토리 방식을 좋아합니다.
이 라이브러리 https://github.com/lukemorales/query-key-factory 를 사용하면 좋겠다.. 라는 생각만 하고있습니다
(저도 현재 스타만 눌러놓고 안써봤습니다)

2024-03-03 07:36 UTC, yogjin commented on src/pages/profile/Profile.page.tsx
> +                <Suspense fallback={<></>}>
탭 내용물을 가져올때 응답시간이 빨라서, 그 찰나에 Spinner를 보여준다면 유저가 오히려 스트레스를 받는다고 생각했습니다.
그래서 그냥 빈 화면으로 보여주는 게 낫지 않을까 싶어 일단 빈 태그로 두었습니다.
응답시간이 300ms이상이 되기 전에는 Spinner나 Skeleton을 보여주지 않는게 괜찮을까.. 생각하는 등 사실 Suspense 부분에 대해 고민이 많은데, 그런 디테일한 부분까지 신경쓸 시간이 없어 일단 이슈에 todo로 남겨두었습니다.

2024-03-03 07:39 UTC, yogjin commented on src/pages/components/NewIdeaCard/NewIdeaCard.tsx
> +    </NewIdeaCardContext.Provider>
넵 맞습니다.
그런데 사실 현 시점에서 prop 관련 마음에 들지않는 부분이 있어 수정이 필요할 듯한데, 이것도 이슈로 추가해 todo로 남겨두겠습니다.

2024-03-03 07:49 UTC, yogjin commented on src/pages/components/NewIdeaCard/NewIdeaCardContext.tsx
> +
그러네요. postfix 추가하겠습니다!
tsx인 이유는 초기버전에 Provider까지 만들어서 export학 있어서 그랬습니다.
그런데 그럴 필요가 없다고 판단해서 지웠는데, 확장자를 바꾸지 못했네요.
지적 감사합니다.

2024-03-03 08:08 UTC, yogjin commented on src/pages/components/NewIdeaCard/compound/Footer/Footer.tsx
> +  };
`get999PlusCount` 로 빼보았습니다.

2024-03-03 08:13 UTC, yogjin commented on src/pages/feed/types/index.ts
> +  createdAt: string; // 생성시각,
스프링에서 만들어진 Date 타입은 프론트로 내려올때 string타입으로 변환되어 내려옵니다.
그래서 결국 프론트에서 new Date(createdAt)으로 사용해야하더라구요.
저 부분을 Date 타입으로 바꾸면 사용에 혼동이 있어서 string으로 바꿨습니다.
저도 처음엔 헷갈리던 부분이라, 혹시 잘못된 부분이 있을까요?

2024-03-03 12:07 UTC, yogjin commented on src/pages/feed/components/BestIdeaCardListSection/BestIdeaCardListSection.tsx
> +      </Suspense>
네 맞습니다

2024-03-03 12:07 UTC, yogjin commented on src/pages/components/NewIdeaCard/compound/Content/Content.tsx
> +  const isTeamRecruitmentsExist = teamRecruitments.length > 0;
teamRecruitments 가 skillCategories로 변경되었네요. 
api 대조해가며 대응 완료했습니다.
참고 PR: https://github.com/ConceptBe/conceptbe-backend/pull/34

2024-03-05 10:31 UTC, semnil5202 approved these changes
고생많았습니다~~! 정상적으로 동작하는 것 확인했습니다. 추후에 같이 디자인 시스템 처리해보죠..

내 프로필 페이지에서 배경이 많이 깨지네요. 아마 무현님이 이미지 사이즈를 작게 두신 것 같은데 이 부분은 한 번 의논이 필요할 것 같습니다.

![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/1912d80c-f1be-49e9-b4fd-c1039575f46d)

가로 세로 375px 300px 이네요.

2024-03-05 10:31 UTC, semnil5202 commented on src/pages/feed/components/FilterBottomSheet/FilterBottomSheet.tsx
> +    });
한 폼당 하나의 훅으로 상태를 관리하고자 했던게 제 use 훅 시리즈여서 위 로직은 아래처럼 수정해볼 수 있겠습니다만, 적용하지는 말아주세요~

```suggestion
  const { dropdownValue, onClickDropdown } = useDropdown({
    recruitmentPlace: recruitmentPlaces.find((place) => place.id === filterParams?.recruitmentPlaceId)?.name ?? '',
    skillCategory1Depth : filterParams?.skillCategoryIds?.[0] !== undefined
          ? getSkillCategory1DepthFrom2DepthSkillId(filterParams?.skillCategoryIds?.[0]).name
          : undefined ?? '',
    skillCategory2Depth : filterParams?.skillCategoryIds?.[0] !== undefined
          ? get2DepthNameFrom2DepthId(filterParams?.skillCategoryIds?.[0])
          : undefined ?? '',
  });
```
필터링이 되어있으면 이전 필터링 값을 적용해야하다보니 불필요한 로직이 많이 발생되는군요. 문제점을 잘 파악했습니다.

2024-03-05 10:31 UTC, semnil5202 commented on src/pages/feed/components/FilterBottomSheet/FilterBottomSheet.tsx
> +  const { dropdownValue: skillCategory1DepthDropDownValue, onClickDropdown: onCklickSkillCategory1DepthDropDown } =
⚠️ onCklick 오타 있습니다. 하단의 onCklick ~ 2Depth 메서드에도 오타 있습니다.

2024-03-05 10:31 UTC, semnil5202 commented on src/pages/feed/context/filterContext.tsx
> +export const useFilterParams = () => {
요 부분에 아래와 같은 경고가 발생하지만, 컨텍스트를 사용하는 훅을 정의해서 내보내는 방식이 좋다고 생각하고 해당 훅만 따로 빼서 사용하기 애매하니 우선 이렇게 두는 방향으로 진행하면 될 것 같습니다.

![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/0795717a-a011-4672-97ef-7fcae3806d3c)

2024-03-05 10:31 UTC, semnil5202 commented on src/pages/feed/hooks/mutations/useDeleteBookmarkIdea.ts
> +      queryClient.invalidateQueries({ queryKey: ['members', 'detail', memberId, 'bookmarkedIdeas'] });
호옹 우아콘에서 잠깐 발표했던 그 라이브러리인가요? 시간이 나면 한 번 적용해보면 좋겠군요. 키 관리가 체계적이면 더 좋겠다고 생각해서 👍

2024-03-05 10:31 UTC, semnil5202 commented on src/pages/feed/types/index.ts
> +  createdAt: string; // 생성시각,
아하 그렇군요?! 처음 알았습니다. 저도 반영해두어야겠습니다.

2024-03-05 10:31 UTC, semnil5202 commented on src/pages/profile/Profile.page.tsx
> +                <Suspense fallback={<></>}>
아하 이 곳에 추후에 useTansition 등을 활용해볼 수 있겠군요. 정확하게 기억나는 것은 아니지만 useTransition을 활용해서 위와 같은 짧은 주기의 UI 업데이트를 동시적으로 처리하여 스피너를 생략할 수 있게할 수 있었던 것 같습니다. 자세한 건 저도 더 알아봐야할 것 같습니다.

2024-03-05 10:31 UTC, semnil5202 commented on src/pages/components/NewIdeaCard/compound/Profile/Profile.tsx
> +          </Box>
넵 아마 타입쪽에서 에러도 발생할 것 같네요. SVG는 ReactComponent로 인식되어서 as string 을 하지 않는 이상..

2024-03-05 10:31 UTC, semnil5202 commented on src/pages/feed/components/BestIdeaCardListSection/BestIdeaCardListSection.tsx
> +      </Suspense>
아하 처음엔 한 파일에 컴포넌트가 두 개여서 무언가 어색한 느낌을 받았는데 계속 보니 오히려 컴포넌트 역할 분리 측면에서 더 괜찮은 방법인 것 같군요. 조수미다. 👍

2024-03-05 11:02 UTC, merged