Feat/#37: 게시글 상세 댓글, 좋아요, 스크랩 기능 구현
ConceptBe/conceptbe-frontend pull request #53
Opened 2024-03-06 20:27 UTC by semnil5202

## 📄 Summary
close #37

> 게시글 상세 댓글, 대댓글, 좋아요, 스크랩 기능을 구현합니다.

## 🙋🏻 More

> 서버와 실 연동 작업이 필요합니다. 몇몇 기능이 동작하지 않습니다. 자세한 내용은 이슈에서 확인 가능합니다.

2024-03-08 15:37 UTC, yogjin requested changes
수고하셨습니다. 로직이 많아서 눈에 띄는 것 위주로 짧게 리뷰했습니다!

2024-03-08 15:37 UTC, yogjin commented on src/pages/FeedDetail/hooks/mutations/usePostCommentMutation.ts
> +export default usePostCommentMutation;
onSuccess를 prop으로 또 선언을 해줄필요가 없습니다.
...rest로 넘겨주었기 때문에, mutation 사용처에서 option으로 onSuccess 콜백을 선언해주면, 알아서 처리가 되더라구요.
사실 저도 처음 react-query쓸 때 같은 실수를 했습니다😄

2024-03-08 15:37 UTC, yogjin commented on src/pages/FeedDetail/hooks/mutations/usePatchCommentMutation.ts
> +const usePatchCommentMutation = ({ feedId, commentId, onSuccess }: Props) => {
저는 mutation은 따로 뒤에 붙이지 않는 편입니다. 
Patch, Post, Put 처럼 앞에서 붙여져 있기 때문인데요, 이건 취향차이라고 생각합니다.

2024-03-08 15:37 UTC, yogjin commented on src/pages/FeedDetail/FeedDetail.page.tsx
> +    <CommentFocusProvider>
이게 어떤역할을 하나요?

2024-03-08 15:37 UTC, yogjin commented on src/pages/FeedDetail/components/Comments.tsx
> +        <Fragment key={comment.content}>
key를 `comment.parentCommentId` 로 하는건 어떤가요?

2024-03-08 15:37 UTC, yogjin commented on src/pages/FeedDetail/contexts/CommentFocusContext.tsx
> +};
와우.... 스크롤하는 부분 로직 같은데 복잡하네요ㅋㅋㅋㅋ

2024-03-08 15:37 UTC, yogjin commented on src/pages/FeedDetail/hooks/mutations/useDeleteScrapMutation.ts
> +      queryClient.invalidateQueries({ queryKey: ['feedDetail', id] });
queryKey 선언 방식이 약간 어색하게 느껴집니다.
['feeds', 'detail', id] 는 어떤가요?

2024-03-08 15:37 UTC, yogjin commented on src/pages/FeedDetail/hooks/mutations/usePostCommentMutation.ts
> +export default usePostCommentMutation;
queryKey ['comments', feedId] 부분이 잘 이해가 되지 않습니다. 해석 가능할까요?

2024-03-08 15:39 UTC, yogjin commented on src/pages/FeedDetail/components/Comment.tsx
> +        <Recomment key={idx} feedId={feedId} recomment={recomment} myImageUrl={myImageUrl} myNickname={myNickname} />
이 부분도 key로 `recomment.childCommentId`는 어떨까요

2024-03-08 16:25 UTC, semnil5202 commented on src/pages/FeedDetail/FeedDetail.page.tsx
> +    <CommentFocusProvider>
요 부분이 아래 세 가지 기능을 컨트롤 합니다.

1. 댓글 입력창 상태 관리 및 포커싱, 포커싱 아웃 로직 관리 (댓글 맨 위 상단의 댓글 입력창)
2. 대댓글 입력창 포커싱, 포커싱 아웃 로직 관리 (각 댓글 마다 생성 가능한 대댓글 입력창)
3. 댓글 및 대댓글 수정 입력창 포커싱, 포커싱 아웃 로직 관리 (각 댓글, 대댓글 수정 시 보이는 입력창)

2번과 3번은 동일하게 생겼지만 1번이 조금 특이합니다. 1번의 경우에는 게시글 상세 통 틀어서 하나의 입력창이고 입력 값에 따라서 댓글창을 확장할지 축소할지 등의 로직이 추가됩니다. 그래서 컨텍스트 내부에 1번 입력창의 상태가 있고 2번, 3번 입력창은 각 컴포넌트의 로컬 상태로 관리됩니다. (각 댓글, 대댓글 마다 생성해야하므로)

위 기능을 관리하는 컨텍스트가 되겠습니다.

2024-03-08 16:25 UTC, semnil5202 commented on src/pages/FeedDetail/components/Comment.tsx
> +        <Recomment key={idx} feedId={feedId} recomment={recomment} myImageUrl={myImageUrl} myNickname={myNickname} />
오우 좋습니다. id 값이 서버에 반영되기 전에 로직을 미쳐 수정하지못했군요. 수정해두겠습니다.

2024-03-08 16:25 UTC, semnil5202 commented on src/pages/FeedDetail/components/Comments.tsx
> +        <Fragment key={comment.content}>
이 부분 역시 수정해두겠습니다.

2024-03-08 16:25 UTC, semnil5202 commented on src/pages/FeedDetail/contexts/CommentFocusContext.tsx
> +};
네 이 부분이 좀 많이 어지러운데 그렇다고 컨텍스트를 여러개로 나눠서 컨텍스트 세 개를 감싸자니 좀 애매하고..

그래서 로직은 한 곳으로 몰아두고 커스텀 훅을 활용해서 가져오는 값을 제한하는 방식으로 진행했습니다.

2024-03-08 16:25 UTC, semnil5202 commented on src/pages/FeedDetail/hooks/mutations/useDeleteScrapMutation.ts
> +      queryClient.invalidateQueries({ queryKey: ['feedDetail', id] });
오우 좋습니다. 반영해둘께요.

2024-03-08 16:25 UTC, semnil5202 commented on src/pages/FeedDetail/hooks/mutations/usePatchCommentMutation.ts
> +const usePatchCommentMutation = ({ feedId, commentId, onSuccess }: Props) => {
오호 저도 Mutation postfix를 계속 붙이다보니 네이밍이 너무 길어지더군요. Delete, Patch, Put 키워드를 삭제하자니 기능이 제대로 명시가 안되는 것 같고..

Mutation postfix 일괄 삭제할께여~

2024-03-08 16:25 UTC, semnil5202 commented on src/pages/FeedDetail/hooks/mutations/usePostCommentMutation.ts
> +export default usePostCommentMutation;
아하 사용처에서 option으로 onSuccess 콜백을 선언해준다는게 어떻게 사용되는 것인지 알 수 있을까여? 처음 안 사실이군요

2024-03-08 16:25 UTC, semnil5202 commented on src/pages/FeedDetail/hooks/mutations/usePostCommentMutation.ts
> +export default usePostCommentMutation;
댓글 무한스크롤 조회 쿼리키 입니다. 각 게시글 id 값으로 댓글을 조회하고 있는데, 댓글을 작성하거나 삭제한 후 해당 쿼리 키를 무효화하여 댓글 리스트를 최신화 하고 있습니다.

2024-03-08 16:25 UTC, semnil5202 commented
추가로 현재 서버에서 댓글 및 대댓글 좋아요, 좋아요 해제 기능이 도입되어서 이 부분과 리팩토링을 같이 반영해두도록 하겠습니다.

2024-03-09 06:55 UTC, yogjin commented on src/pages/FeedDetail/hooks/mutations/usePostCommentMutation.ts
> +export default usePostCommentMutation;
그렇군요. 더 나은 쿼리키 선언 방법이 있는지 고민해보면 좋을 것 같아요.
저도 당장은 모르겠는데, comments 뒤에 feed의 id가 나오니까 조금 어색한 느낌이 들었네요

2024-03-09 08:46 UTC, yogjin approved these changes
수고하셨어요

2024-03-09 08:51 UTC, merged