Feat/#54: Alert, Confirm 컴포넌트 구현 및 ErrorBoundary 적용
ConceptBe/conceptbe-frontend pull request #56
Opened 2024-03-07 20:50 UTC by semnil5202

## 📄 Summary

close #54

> toss/use-overlay를 활용하여 Alert, Confirm 컴포넌트 구현 및 ErrorBoundary, NotFound 적용

추가로 SignUp 페이지에서 직장명, 자기소개에 닉네임 유효성 검사 로직이 잘못 들어간 오류를 수정하고 구현한 Alert 컴포넌트를 적용합니다.

디자인 시스템 0.4.5로 업데이트(PNG, SVG 추가 및 자잘한 스타일 오류) 적용했습니다.

## 🙋🏻 More

> ApiErrorBoundary 쓰임새에 대해서 의논해보면 좋겠습니다.

GlobalErrorBoundary와 NotFound는 만일의 상황에 대비한 컴포넌트이기에 적용하는데 별다른 의문이 들지 않았습니다만, ApiErrorBoundary를 활용할 때가 있을지 의문이 들더군요.

결론적으로 Mutation 하는 로직에선 useOverlay 훅을 사용하여 에러를 처리하고 Get(Query) 해오는 에러에서 ApiErrorBoundary를 사용해보면 어떨까 입니다.

서버에서 Get 해오는데 에러가 발생한다는 것은 사용자의 오류보단 서버에 오류가 있는 경우가 더 많으므로 Alert 등의 컴포넌트를 사용하지 않고 바로 Fallback 컴포넌트를 보여줄 수 있도록 했습니다.

아래는 각 에러 상황에 따른 적용 이미지 입니다.

2024-03-09 02:28 UTC, yogjin requested changes
몇 가지 남겨보았습니다.

2024-03-09 02:28 UTC, yogjin commented on src/components/ErrorBoundary/ErrorFallback.tsx
> +        >
인라인 스타일이 조금 아쉬운데, 다른 방법은 없을까요?

2024-03-09 02:28 UTC, yogjin commented on src/hooks/useConfrim.tsx
> +  return { openConfirm, openPromiseConfirm };
openConfirm, openPromiseConfirm 두개를 작성하셨는데, 어떤차이가 있나요?

2024-03-09 02:28 UTC, yogjin commented on src/pages/SignUp/SignUp.page.tsx
> -
유효성 검사를 삭제한 이유가 궁금합니다

2024-03-09 02:28 UTC, yogjin commented on src/components/ErrorBoundary/ApiErrorBoundary.tsx
이 컴포넌트의 용도가 궁금하네요.
mutation은 각 onError 콜백에서 처리한다고 가정하고
get 에러인 경우에만 커버한다고 했을때, 화면 전체를 감싸는것이 좋은가? 에 대해서 논의해보면 좋을듯 합니다.

2024-03-09 02:28 UTC, yogjin commented on src/components/ErrorBoundary/GlobalErrorBoundary.tsx
현재 모든 GET 400 500 에러에 대해 이 에러바운더리가 보이는 게 맞을까요?
만약 그렇다면 react query 의 query도 reset를 해야할 것 같습니다.

2024-03-09 02:30 UTC, yogjin commented
> 결론적으로 Mutation 하는 로직에선 useOverlay 훅을 사용하여 에러를 처리하고 Get(Query) 해오는 에러에서 ApiErrorBoundary를 사용해보면 어떨까 입니다.

useOverlay 훅을 이용해서 에러를 처리한다는게, 어떤 의미인가요?

2024-03-09 09:06 UTC, semnil5202 commented on src/components/ErrorBoundary/ApiErrorBoundary.tsx
네 맞습니다. GET 에러의 경우 토스트나 알럿을 사용하지 않고 APIErrorBoundary로 일괄처리하는게 좋을지 저도 고민입니다. 컴포넌트를 구현만 해두었고 적용은 하지 않았으니 추후 논의를 통해 결정해봅시다.

2024-03-09 09:06 UTC, semnil5202 commented on src/components/ErrorBoundary/GlobalErrorBoundary.tsx
오 쿼리 reset은 전혀 생각하지 못했네요. 이 경우에는 상황에 따라 reset 하는 쿼리가 다를테니 에러 바운더리를 사용하는 각 컴포넌트에서 이 Fallback 컴포넌트를 주입할 수 있도록 해야겠군요.

```tsx
<ApiErrorBoundary fallback={<ErrorFallback ...props onReset={'쿼리 키 리셋 로직'} />}>
{children}
</ApiErrorBoundary>
```

위와 같은 형태면 가능할까요? 더 좋은 방법이 있다면 의견 부탁드립니다.

2024-03-09 09:06 UTC, semnil5202 commented on src/hooks/useConfrim.tsx
> +  return { openConfirm, openPromiseConfirm };
confirm의 경우 특성상 사용자 입력에 따라 로직을 달리해야하는 경우가 발생할 것 같습니다. (ex: 동의하십니까? | 예 -> true에 대한 로직 수행 | 아니오 -> false에 대한 로직 수행)
```ts
if(openPromiseConfirm) {
// true 로직
}
// false 로직
```
위와 같은 형태로 사용하기 위해서 Promise를 사용하여 유저 input을 대기할 수 있도록 하였습니다. 프로미스를 사용하지 않으면 유저의 input을 기다리지 않고 다음 로직이 수행되게 됩니다. 상황에 따라 유저의 Input을 기다리지 않고 onConfirm, onClose 파라미터를 통해 수행할 수도 있겠다고 판단하여 위와 같이 두 개의 메서드로 분리하여 작성했습니다.

2024-03-09 09:06 UTC, semnil5202 commented on src/pages/SignUp/SignUp.page.tsx
> -
스읍 이 부분이 조금 고민인데, 저는 서버에서 유효성 검사를 진행하더라도 프론트에서 유효성 검사를 진행하는 걸 선호하는 바입니다. 

제거한 위 로직은 서버에서 유효성 검사를 동일하게 수행하고 거의 동일한 에러 문구를 띄워주고 있습니다. 그래서 onSubmit 로직을 간소하게 가져가고자 제거하였습니다.

프론트 단에서 유효성 검사를 진행하여 실제 서버와 요청이 일어나기 전 차단을 진행할 수 있다는 장점이 있는 점을 인지하고 있습니다. 답글을 작성하다보니 유효성 검사를 다시 두는게 더 좋은 선택인 거 같기도 하네요. 어떻게 생각하시나요?

2024-03-09 09:08 UTC, semnil5202 commented
> useOverlay 훅을 이용해서 에러를 처리한다는게, 어떤 의미인가요?

toss/use-overlay 라이브러리를 통해 생성한 훅으로 에러를 처리한다는 의미였습니다. 뮤테이션 하는 로직은 onError 로직을 작성하므로 onError 함수 내부에서 openAlert와 같은 기능을 활용하여 에러 핸들링을 처리할 것이기 때문입니다. 그에 반해 Get 을 해오는 Query 문에서는 따로 에러 핸들링을 수행하지 않아서 이 부분에 ApiErrorBoundary를 적용하면 어떨까 하는 의견이었습니다.

2024-03-09 10:28 UTC, yogjin commented on src/hooks/useConfrim.tsx
> +  return { openConfirm, openPromiseConfirm };
onConfirm이나 onClose를 수행하려면 무조건 유저 input을 기다려야하지 않나요?

2024-03-09 10:29 UTC, yogjin commented on src/pages/SignUp/SignUp.page.tsx
> -
좋습니다~
저는 서버랑 이야기됐으면 서버에서 에러 내려주는 것도 좋다고 생각합니다.

2024-03-09 10:30 UTC, yogjin commented on src/components/ErrorBoundary/GlobalErrorBoundary.tsx
https://tanstack.com/query/latest/docs/framework/react/reference/QueryErrorResetBoundary 읽어보시면 좋을 것 같아요

2024-03-09 10:33 UTC, yogjin commented on src/components/ErrorBoundary/ApiErrorBoundary.tsx
저는 GET 에러만 생긴 부분만 커버하는 Fallback을 상황에 맞게 주입해주는게 나을지, 아니면 지금처럼 ApiErrorBoundary 내부에 ErrorFallback이 static하게 정해서 화면 전체를 덮는게 나을지 고민이네요. 저는 전자가 더 끌리긴합니다.

2024-03-09 13:17 UTC, semnil5202 commented on src/components/ErrorBoundary/ErrorFallback.tsx
> +        >
아하 Text 컴포넌트가 리액트 컴포넌트다 보니까 Emotion Styled로 재사용하기 어려운 문제점이 있습니다. (추후 수정 예정)

이 부분은 해당 컴포넌트의 로컬 스타일 컴포넌트로 재정의 하여 사용하겠습니다.

2024-03-09 13:19 UTC, semnil5202 commented on src/hooks/useConfrim.tsx
> +  return { openConfirm, openPromiseConfirm };
고민해보았는데 Alert를 두고 Confirm을 사용하는 경우는 무조건 유저의 input을 기다리는 상황이라고 판단됩니다. 따라서 openConfirm을 Promise로 활용하여 구현해두고 openPromiseConfirm은 제거하도록 하겠습니다.

2024-03-09 15:24 UTC, yogjin approved these changes

2024-03-11 03:39 UTC, semnil5202 commented on src/components/ErrorBoundary/GlobalErrorBoundary.tsx
오호.. 이런 야무진 기능이 있었군요. 공유 감사드립니다 👍 그러면 제가 이해한 바로는 GlobalErrorBoundary 윗 단에 QueryErrorResetBoundary를 두면 좋을 것 같은데 어떤가요?

2024-03-11 20:06 UTC, semnil5202 commented
develop rebase 후 force push 진행하였습니다. 위에서 리뷰해주신 내용 반영 완료했습니다.

* QueryErrorResetBoundary를 GlobalErrorBoundary, ApiErrorBoundary에 적용 완료했습니다.
* ApiErrorBoundary에서 fallback prop을 통해 fallback UI Component를 옵셔널로 받을 수 있도록 했습니다. 없을 경우 위에서 작성한 기본 UI가 표시됩니다.

수정해보면서 생각해보니 fallback prop을 넘기지 않았더라면 아래 시연 영상에서도 볼 수 있듯이, 현재 ErrorFallback 컴포넌트의 기본 UI가 페이지 단위라서 무조건 page 단위로만 적용을 해야겠더군요. 예를 들어 댓글 Query만 오류가 나서 ApiErrorBoundary를 감싸면, 댓글 부분에 '일시적인 오류입니다.' UI가 뜨면서 전반적인 레이아웃이 망가질 것 같습니다. 아무튼 fallback prop을 잘 반영한 것 같습니다.

추가로 fallback 컴포넌트 생성시 QueryErrorBoundary의 reset 메서드를 이어 받아야 하므로 아래와 같이 작성하시면 되겠습니다.
```ts
interface Props {
  error: AxiosError;
  resetErrorBoundary: () => void;
}

const FallbackComponent = ({ error, resetErrorBoundary }: Props) => {
  return <></>;
};
```
resetErrorBoundary는 Query reset 함수와 ErrorBoundary state reset 로직이 포함된 함수입니다. error는 FallbackComponent 내부에서 에러별 분기처리 로직을 작성할 가능성도 있어보여서 포함시켰습니다. 이 방식은 react-error-boundary 라이브러리를 참고했습니다. (네이밍도 동일합니다.)

마지막으로 ApiErrorBoundary를 FeedDetailPage에 적용하고 feed detail GET 에러를 발생시켰을 때 화면입니다. **현재는 router 부분에 FeedDetailPage에만 반영해두었는데, 모든 페이지에 반영해둘까요?**

![Mar-12-2024 04-50-23](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/f2b3b148-2996-45d6-815d-6ebadad5c847)

2024-03-11 22:23 UTC, semnil5202 commented
추가로 App에 Suspense 해두신게 ApiErrorBoundary가 발생했을 때 문제가 되는 것 같습니다. query reset이 동작하는데 suspense의 영향을 받다보니 App의 Suspense를 기준으로 동작하더군요. App 아래에 router가 있다보니, 에러가 발생하지 않은 페이지임에도 query reset으로 인해 화면이 갱신되지 않습니다. 다음과 같습니다.

![Mar-12-2024 07-14-58](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/88358580-4682-493d-b0a6-7bfec66e9dab)

따라서 다음과 같이 각 router 컴포넌트를 한 번 더 감싼 고차 컴포넌트 방식이 어떨지 제안드립니다.
```tsx
const wrapPage = (children: ReactNode) => (
  <ApiErrorBoundary>
    <Suspense fallback={<Spinner />}>{children}</Suspense>
  </ApiErrorBoundary>
);

const routes: RouteElement[] = [
  {
    path: '/',
    element: <MobileView />,
    isAuth: false,
    errorElement: <NotFound />,
    children: [
      {
        path: '',
        element: wrapPage(<Feed />),
        withAuth: false,
      },
      {
        path: '/feed/:id',
        element: wrapPage(<FeedDetailPage />),
        withAuth: true,
      },
// ...
```
wrapPage 네이밍도 추천 부탁드립니다.. 도저히 좋은 네이밍이 생각나질 않네요. wrapWithSuspenseErrorBoundary? ㅋㅋㅋㅋㅋ..

2024-03-12 13:00 UTC, yogjin commented
> wrapPage 네이밍도 추천 부탁드립니다.. 도저히 좋은 네이밍이 생각나질 않네요. wrapWithSuspenseErrorBoundary? ㅋㅋㅋㅋㅋ..

`withAsyncBoundary`는 어떨까요

> 현재는 router 부분에 FeedDetailPage에만 반영해두었는데, 모든 페이지에 반영해둘까요?

네 일단 모든 페이지에 적용해줘도 좋을 것 같습니다.

2024-03-12 15:48 UTC, semnil5202 commented
넵 기획 논의 사항 중에 수정 사항 반영 시에 같이 적용해두겠습니다.

오호 withAsyncBoundary 괜찮은 것 같군요. async에서 suspense를 boundary에서 errorBoundary 느낌이 들 수 있겠군요. 👍

2024-03-12 16:27 UTC, merged