Refactor/#81: UI 및 디자인 시스템 관련 오류 및 필터링 초기화 버튼 수정
ConceptBe/conceptbe-frontend pull request #82
Opened 2024-03-23 15:00 UTC by semnil5202

## 📄 Summary

>

## 🙋🏻 More

>

2024-03-25 11:42 UTC, yogjin requested changes
수고하셨습니다, 궁금한점이랑 눈에 보이는 것 조금 리뷰해봤습니다

1. 피드 필터링 바텀시트 초기화 버튼은 추가 예정인가요?
2. 이슈에 프로필 페이지 헤더 영역 고정 문제 -> 미고정으로 변경 (재확인 결과 고정 방식이 맞음) 이게 무슨 뜻인가요?
3. 내 프로필-아이디어도 width 수정이 필요해보입니다
<img width="432" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/b0617893-f047-4698-9319-091af21d1c36">

2024-03-25 11:42 UTC, yogjin commented on src/components/ErrorBoundary/ErrorFallback.tsx
> +      height="100dvh"
100dvh 로 설정했을때 약간 왔다갔다 하는 문제가 있다는 것 같던데, 괜찮았나요?
모바일로 확인해보세요: https://mytory.net/wp-content/codes/vh-test/dist/

2024-03-25 13:01 UTC, semnil5202 commented on src/components/ErrorBoundary/ErrorFallback.tsx
> +      height="100dvh"
아하 네네 100dvh로 하다보면 주소창 크기에 따라 들썩이는 부분이 발생하는데, 에러 페이지는 대부분의 기기에서 하단에 여백이 남아 에러페이지 자체가 들썩거리지는 않습니다.

2024-03-25 13:06 UTC, semnil5202 commented
> 피드 필터링 바텀시트 초기화 버튼은 추가 예정인가요?

엇? 초기화 버튼을 추가해두었는데 보이지 않나요?? UI가 보이지 않는건가여? 아니면 기능적으로 문제가 있는 것일까요? 제 화면은 아래처럼 보이고 기능도 정상 동작하는 걸로 확인했습니다.

<img width="368" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/6b3ae9f6-fe18-440a-af89-038553e27e19">

> 이슈에 프로필 페이지 헤더 영역 고정 문제 -> 미고정으로 변경 (재확인 결과 고정 방식이 맞음) 이게 무슨 뜻인가요?

아 이게 단톡방에서 잠깐 얘기가 나왔던 부분인데, 아래 캡쳐 부분입니다. 아래 QA를 보면서 프로필 페이지에서 Header를 고정하는게 아닌 Static한 방식으로 두어 스크롤 시 가려지도록 해야한다 라고 이해했는데요. 재확인 결과 현재처럼 Header 를 상단에 fixed 하는게 맞다고 합니다. 그래서 저렇게 작성해두었는데 말을 너무 대충 썼었네요.

![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/48cb05b2-a1df-4af6-9245-40299e1505f5)

> 내 프로필-아이디어도 width 수정이 필요해보입니다.

아하 확인해보니 max-width 때는 문제가 없는데 margin으로 인해 내용물이 충분하지 않으면 width가 줄어드는 군요. 수정해서 올려두도록 하겠습니다.

2024-03-26 12:23 UTC, yogjin commented on src/components/ErrorBoundary/ErrorFallback.tsx
> +      height="100dvh"
음 에러 페이지의 높이가 고정이라 밑 부분이 하얗게 채워지는걸까요?
<img width="309" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/159862b0-c50b-41b6-957c-3d614454bb91">

2024-03-28 11:10 UTC, semnil5202 commented on src/components/ErrorBoundary/ErrorFallback.tsx
> +      height="100dvh"
버튼 아래의 하얀 여백 말씀하시는 거져? 네 피그마 시안과 동일하게 두었습니다.

2024-03-29 15:35 UTC, yogjin commented
초기화버튼을 누르고 다시 필터 바텀시트를 열면 이전에 선택한게 그대로 초기값으로 표시되는 문제가 있네요
<img width="422" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/55330e45-42b8-4314-81c2-d290c63812b7">

2024-03-31 09:25 UTC, merged