Feat#88: 글 작성 중 페이지 나갈 경우 '글 작성 종료하시겠습니까?' Confirm 기능 추가
ConceptBe/conceptbe-frontend pull request #90
Opened 2024-04-04 16:22 UTC by yogjin

## 📄 Summary
글 작성중 페이지를 나갈 경우 확인 기능을 추가합니다.

https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/9f9a64dd-a16e-417d-8147-bce8bceed60a

## 🙋🏻 More

> eventlistener 달아서 url 바뀔때, 새로고침때 모두 고려하려고 했으나, 모바일뷰이기도 하고, 굳이 싶은 생각이 들어서 그냥 버튼에만 달았습니다.

2024-04-05 07:47 UTC, semnil5202 requested changes
기능 동작 확인했습니다. 몇 가지 코멘트 남겼어요. 고생 많으셨습니다. 👍

본문에 적어주신 것처럼 새로고침의 경우도 고려해보면 어떨까요? 상하로 스크롤하면서 아래 영상과 같이 의도치 않게 새로고침이 발생하는 경우가 적지는 않을 것 같습니다.

https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/23bd6dfe-2b21-473a-a4b8-d7a855e11ee1

이 부분에 대해서 의견 부탁드립니다. 😇

2024-04-05 07:47 UTC, semnil5202 commented on src/layouts/Back.tsx
> +      : true;
만들어둔 Confrim 컴포넌트를 따로 사용하지 않은 이유가 있을까요?

2024-04-05 07:47 UTC, semnil5202 commented on src/layouts/Back.tsx
> +  const handleBackClick = () => {
아무것도 입력하지 않았을 때는 바로 뒤로가기가 되는것이 사용자가 예상한 동작에 가깝지 않을까요?

입력 중 의도하지 않은 뒤로가기일 경우만 Confirm을 활용하는 것이 좋아보입니다. 이 부분에 대해서 어떻게 생각하시나용?

2024-04-08 13:37 UTC, yogjin commented on src/layouts/Back.tsx
> +      : true;
허허.. 깜박하고있었네요

2024-04-08 13:38 UTC, yogjin commented on src/layouts/Back.tsx
> +  const handleBackClick = () => {
음.. 그게 좋겠네요

2024-04-08 15:49 UTC, yogjin commented
> 본문에 적어주신 것처럼 새로고침의 경우도 고려해보면 어떨까요? 상하로 스크롤하면서 아래 영상과 같이 의도치 않게 새로고침이 발생하는 경우가 적지는 않을 것 같습니다.

고려하면 좋을 것 같네요.
다만.. 지금 버그 쌓인게 좀 많아서, 해당사항은 우선순위를 뒤로 미뤄도 좋을 것 같습니다.

아무것도 입력하지 않았을때 Confirm 창 띄우도록 수정했습니다!
https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/1c857021-f382-41d6-8c6b-42f248bd5c0a

2024-04-12 14:49 UTC, semnil5202 approved these changes
고생하셨습니다. 변경사항 확인했습니다. 👍

2024-04-13 12:08 UTC, merged